#!/bin/bash
# Script untuk clear browser cache dan hard refresh

echo "=== KEP Cache Buster ==="
echo ""
echo "Step 1: Hapus browser cache dengan membuka DevTools"
echo "  - Buka browser ke: http://localhost:3000"
echo "  - Tekan F12 atau Ctrl+Shift+I (buka DevTools)"
echo "  - Klik tab Network"
echo "  - Centang checkbox 'Disable cache'"
echo "  - Tetap buka DevTools saat testing"
echo ""
echo "Step 2: Hard Refresh Browser"
echo "  - Windows: Ctrl + Shift + R (keep pressing until see changes)"
echo "  - Mac: Cmd + Shift + R"
echo "  - Or: Ctrl + F5"
echo ""
echo "Step 3: Clear Local Storage & Session"
echo "Paste ini di Console (F12 → Console):"
echo ""
echo "localStorage.clear(); sessionStorage.clear(); location.reload();"
echo ""
echo "Step 4: Test Upload"
echo "  - Go to /presensi"
echo "  - Click 'Upload PDF'"
echo "  - Keep DevTools Console open"
echo "  - Look for '[KEP]' log messages"
echo "  - Try upload batch"
echo ""
echo "Step 5: Screenshot error if still fails"
echo "  - Take screenshot of Console output"
echo "  - Send to developer"
