-- Detail pegawai: tabel riwayat untuk tab yang dikelola pegawai sendiri (self-service)
-- pendidikan : tab Pendidikan (riwayat pendidikan)
-- riwayat_pangkat : tab Riwayat Pangkat
-- diklat_pegawai : tab Diklat

create table if not exists public.pendidikan (
  id bigint generated by default as identity primary key,
  pegawai_id bigint not null references public.pegawai(id) on delete cascade,
  jenjang text,
  jurusan text,
  nama_sekolah text,
  tahun_lulus text,
  ipk text,
  keterangan text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.riwayat_pangkat (
  id bigint generated by default as identity primary key,
  pegawai_id bigint not null references public.pegawai(id) on delete cascade,
  pangkat text,
  golongan text,
  tmt text,
  nomor_sk text,
  keterangan text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.diklat_pegawai (
  id bigint generated by default as identity primary key,
  pegawai_id bigint not null references public.pegawai(id) on delete cascade,
  jenis text not null default 'teknis',
  nama_diklat text,
  penyelenggara text,
  tahun text,
  durasi text,
  keterangan text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_pendidikan_pegawai on public.pendidikan(pegawai_id);
create index if not exists idx_riwayat_pangkat_pegawai on public.riwayat_pangkat(pegawai_id);
create index if not exists idx_diklat_pegawai_pegawai on public.diklat_pegawai(pegawai_id);
